# -*- coding: utf-8 -*-
"""supply_chain_with_Gurobi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JIRvj_76af7lJt8X7-RbZdrqFME9yUci
"""

!pip install gurobipy

# ------------------------
# Import libraries
# ------------------------
import gurobipy as gp
from gurobipy import GRB
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ------------------------
# Data with additional features
# ------------------------

factories = ["F1", "F2"]
customers = ["C1", "C2", "C3", "C4"]

capacity = {
    "F1": 100,
    "F2": 120
}

demand = {
    "C1": 50,
    "C2": 40,
    "C3": 60,
    "C4": 30
}

# Fixed transportation costs
transport_cost = {
    ("F1", "C1"): 4,
    ("F1", "C2"): 6,
    ("F1", "C3"): 9,
    ("F1", "C4"): 5,
    ("F2", "C1"): 5,
    ("F2", "C2"): 4,
    ("F2", "C3"): 7,
    ("F2", "C4"): 6
}

# Additional data for extended features
fixed_costs = {
    "F1": 1000,  # Fixed cost if factory F1 is used
    "F2": 1200   # Fixed cost if factory F2 is used
}

# Variable production costs
prod_cost = {
    "F1": 2,  # Production cost per unit at F1
    "F2": 3   # Production cost per unit at F2
}

# ------------------------
# Model with enhanced features
# ------------------------

def create_transportation_model(include_fixed_costs=False, include_prod_costs=False):
    """
    Create transportation model with optional features
    """
    model = gp.Model("Enhanced_Supply_Chain")

    # Decision variables
    x = model.addVars(factories, customers, lb=0, ub=GRB.INFINITY,
                      name="shipment")

    # Optional binary variables for fixed costs
    if include_fixed_costs:
        y = model.addVars(factories, vtype=GRB.BINARY, name="use_factory")

    # Objective function components
    transport_cost_term = gp.quicksum(transport_cost[f, c] * x[f, c]
                                      for f in factories for c in customers)

    obj_terms = [transport_cost_term]

    if include_prod_costs:
        prod_cost_term = gp.quicksum(prod_cost[f] * x[f, c]
                                     for f in factories for c in customers)
        obj_terms.append(prod_cost_term)

    if include_fixed_costs:
        fixed_cost_term = gp.quicksum(fixed_costs[f] * y[f] for f in factories)
        obj_terms.append(fixed_cost_term)

    model.setObjective(gp.quicksum(obj_terms), GRB.MINIMIZE)

    # Factory capacity constraints
    for f in factories:
        lhs = gp.quicksum(x[f, c] for c in customers)
        model.addConstr(lhs <= capacity[f], name=f"capacity_{f}")

        # Linking constraints for fixed costs
        if include_fixed_costs:
            total_shipments = gp.quicksum(x[f, c] for c in customers)
            # If any shipment from factory f, then y[f] must be 1
            # Using a large enough M (Big-M method)
            M = sum(demand.values())  # Total demand
            model.addConstr(total_shipments <= M * y[f], name=f"link_{f}")

    # Demand constraints
    for c in customers:
        model.addConstr(
            gp.quicksum(x[f, c] for f in factories) == demand[c],
            name=f"demand_{c}"
        )

    # Optional: Add minimum shipment constraints to avoid very small shipments
    min_shipment = 1.0
    for f in factories:
        for c in customers:
            # Either ship 0 or at least min_shipment
            # This requires binary variables - commented out for now
            pass

    return model, x

# ------------------------
# Solve and analyze
# ------------------------

# Create and solve base model
model, x = create_transportation_model(include_fixed_costs=False,
                                       include_prod_costs=False)

# Set solver parameters for better performance
model.Params.TimeLimit = 60  # seconds
model.Params.MIPGap = 0.01   # 1% optimality gap
model.Params.OutputFlag = 1  # Show solver output

# Solve
model.optimize()

# ------------------------
# Comprehensive Results
# ------------------------

if model.status == GRB.OPTIMAL:
    print("\n" + "="*60)
    print("OPTIMAL SOLUTION FOUND")
    print("="*60)

    print(f"\nOptimal Total Cost: ${model.objVal:,.2f}")

    # Create results dataframe
    results = []
    for f in factories:
        for c in customers:
            val = x[f, c].X
            if val > 1e-6:
                results.append({
                    'Factory': f,
                    'Customer': c,
                    'Units': val,
                    'Unit_Cost': transport_cost[f, c],
                    'Total_Cost': val * transport_cost[f, c]
                })

    df_results = pd.DataFrame(results)

    print("\n" + "-"*60)
    print("SHIPMENT PLAN")
    print("-"*60)
    print(df_results.to_string(index=False))

    # Summary statistics
    print("\n" + "-"*60)
    print("SUMMARY STATISTICS")
    print("-"*60)

    # Factory utilization
    print("\nFactory Utilization:")
    for f in factories:
        total_shipped = sum(x[f, c].X for c in customers)
        utilization = (total_shipped / capacity[f]) * 100
        print(f"  {f}: {total_shipped:.1f}/{capacity[f]} units ({utilization:.1f}%)")

    # Customer satisfaction
    print("\nCustomer Demand Satisfaction:")
    for c in customers:
        total_received = sum(x[f, c].X for f in factories)
        print(f"  {c}: {total_received:.1f}/{demand[c]} units")

    # Cost breakdown
    print("\nCost Breakdown:")
    total_transport = sum(row['Total_Cost'] for _, row in df_results.iterrows())
    print(f"  Transportation Cost: ${total_transport:,.2f}")

    # Shadow prices (dual variables)
    print("\n" + "-"*60)
    print("SHADOW PRICES (Dual Variables)")
    print("-"*60)

    print("\nFactory Capacity Shadow Prices:")
    for f in factories:
        constr = model.getConstrByName(f"capacity_{f}")
        if constr:
            print(f"  {f}: ${constr.Pi:.2f} per additional unit of capacity")

    print("\nCustomer Demand Shadow Prices:")
    for c in customers:
        constr = model.getConstrByName(f"demand_{c}")
        if constr:
            print(f"  {c}: ${constr.Pi:.2f} per unit of demand")

    # Reduced costs
    print("\n" + "-"*60)
    print("REDUCED COSTS")
    print("-"*60)
    print("\nNon-basic variables (opportunity cost of not using a route):")
    for f in factories:
        for c in customers:
            rc = x[f, c].RC
            if abs(rc) > 1e-6:  # Non-zero reduced cost
                print(f"  {f}→{c}: ${rc:.2f}")

    # ------------------------
    # Visualization
    # ------------------------

    fig, axes = plt.subplots(2, 2, figsize=(15, 12))

    # 1. Shipment quantities heatmap
    shipment_matrix = np.zeros((len(factories), len(customers)))
    for i, f in enumerate(factories):
        for j, c in enumerate(customers):
            shipment_matrix[i, j] = x[f, c].X

    sns.heatmap(shipment_matrix,
                xticklabels=customers,
                yticklabels=factories,
                annot=True, fmt='.1f',
                cmap='YlOrRd', ax=axes[0, 0])
    axes[0, 0].set_title('Shipment Quantities')
    axes[0, 0].set_xlabel('Customers')
    axes[0, 0].set_ylabel('Factories')

    # 2. Factory utilization pie chart
    factory_util = [sum(x[f, c].X for c in customers) / capacity[f]
                    for f in factories]
    axes[0, 1].pie(factory_util, labels=factories, autopct='%1.1f%%',
                   startangle=90, colors=['lightblue', 'lightgreen'])
    axes[0, 1].set_title('Factory Capacity Utilization')

    # 3. Cost per route bar chart
    routes = [f"{f}→{c}" for f in factories for c in customers
              if x[f, c].X > 1e-6]
    costs = [x[f, c].X * transport_cost[f, c]
             for f in factories for c in customers
             if x[f, c].X > 1e-6]

    if routes:
        y_pos = np.arange(len(routes))
        axes[1, 0].barh(y_pos, costs)
        axes[1, 0].set_yticks(y_pos)
        axes[1, 0].set_yticklabels(routes)
        axes[1, 0].set_xlabel('Cost ($)')
        axes[1, 0].set_title('Cost per Route')

    # 4. Supply-Demand balance
    factory_total = [sum(x[f, c].X for c in customers) for f in factories]
    customer_total = [sum(x[f, c].X for f in factories) for c in customers]

    x_pos = np.arange(len(factories))
    width = 0.35
    axes[1, 1].bar(x_pos - width/2, [capacity[f] for f in factories],
                   width, label='Capacity', alpha=0.7)
    axes[1, 1].bar(x_pos + width/2, factory_total,
                   width, label='Shipped', alpha=0.7)
    axes[1, 1].set_xlabel('Factories')
    axes[1, 1].set_ylabel('Units')
    axes[1, 1].set_title('Factory Supply vs Capacity')
    axes[1, 1].set_xticks(x_pos)
    axes[1, 1].set_xticklabels(factories)
    axes[1, 1].legend()

    plt.tight_layout()
    plt.show()

    # Export results to Excel
    with pd.ExcelWriter('transportation_results.xlsx') as writer:
        df_results.to_excel(writer, sheet_name='Shipment_Plan', index=False)

        # Summary sheet
        summary_data = {
            'Metric': ['Total Cost', 'Total Units Shipped', 'Number of Active Routes'],
            'Value': [model.objVal,
                     df_results['Units'].sum(),
                     len(df_results)]
        }
        pd.DataFrame(summary_data).to_excel(writer, sheet_name='Summary', index=False)

    print("\nResults exported to 'transportation_results.xlsx'")

elif model.status == GRB.INFEASIBLE:
    print("Model is infeasible. Computing IIS...")
    model.computeIIS()
    model.write("model.ilp")
    print("IIS written to model.ilp")

    # Find minimum cost to satisfy demand by relaxing constraints
    print("\nAttempting to find feasible solution by relaxing constraints...")
    model.feasRelax(0, True, False, True)
    model.optimize()

else:
    print(f"Model status: {model.status}")

# ------------------------
# Sensitivity Analysis
# ------------------------

def sensitivity_analysis(base_model, x):
    """
    Analyze sensitivity to parameter changes
    """
    print("\n" + "="*60)
    print("SENSITIVITY ANALYSIS")
    print("="*60)

    # Vary demand and see impact on cost
    demand_multipliers = [0.8, 0.9, 1.0, 1.1, 1.2]
    costs = []

    for mult in demand_multipliers:
        # Create a new model with scaled demand
        model_sens = gp.Model("Sensitivity")
        x_sens = model_sens.addVars(factories, customers, lb=0, name="shipment")

        # Objective
        model_sens.setObjective(
            gp.quicksum(transport_cost[f, c] * x_sens[f, c]
                       for f in factories for c in customers),
            GRB.MINIMIZE
        )

        # Constraints with scaled demand
        for f in factories:
            model_sens.addConstr(
                gp.quicksum(x_sens[f, c] for c in customers) <= capacity[f]
            )

        for c in customers:
            model_sens.addConstr(
                gp.quicksum(x_sens[f, c] for f in factories) == demand[c] * mult
            )

        model_sens.optimize()

        if model_sens.status == GRB.OPTIMAL:
            costs.append(model_sens.objVal)
        else:
            costs.append(None)

    # Plot sensitivity
    plt.figure(figsize=(10, 6))
    plt.plot(demand_multipliers, costs, 'bo-', linewidth=2, markersize=8)
    plt.xlabel('Demand Multiplier')
    plt.ylabel('Total Cost ($)')
    plt.title('Sensitivity to Demand Changes')
    plt.grid(True, alpha=0.3)
    plt.show()

# Run sensitivity analysis
sensitivity_analysis(model, x)

print("\nOptimization completed successfully!")